name: feeby
display_name: Feeby template
version: 1.0.0
parent: at_movic
assets:
  use_parent_assets: false
  css:
    all:
      - id: main-style
        path: assets/css/styles.min.css
      - id: menu-style
        path: assets/css/menu.css

global_settings:
  hooks:
    custom_hooks:
      - name: displayProductThumbEndCustom
        title: Product Custom Thubnail on End
        description: Add custom image on end