name: feeby
display_name: Feeby template
version: 1.0.0
parent: at_movic
assets:
  use_parent_assets: false
  css:
    all:
      - id: main-style
        path: assets/css/styles.min.css
      - id: menu-style
        path: assets/css/menu.css
      - id: swiper-styles
        path: assets/css/swiper.css
  js:
    all:
     - id: swiper-js
       path: assets/js/swiper.js

#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#   js:
#     all:
#       - id: core.js
#         path: assets/js/core.js