name: feeby
display_name: Feeby template
version: 1.0.0
parent: at_movic
assets:
  use_parent_assets: false
  css:
    all:
      - id: main-style
        path: assets/css/styles.min.css
      - id: menu-style
        path: assets/css/menu.css
      - id: swiper-style
        path: assets/css/swiper.css
  js:
    order:
      - id: jquery-plugin-mask-js
        path: assets/js/jquery.mask.min.js
    product:
      - id: adding-to-cart-anim-js
        path: assets/js/adding-to-cart-anim.js
      - id: product-configure-js
        path: assets/js/product-configure.js
    all:
      - id: swiper-js
        path: assets/js/swiper.js
      - id: sharer-js
        path: assets/js/sharer.js
        position: bottom
      - id: loader-js
        path: assets/js/loader.js
      - id: lazy-js
        path: assets/js/lazy.js
        position: bottom
        priority: 8001
      - id: fancybox-jquery-plugin-js
        path: assets/js/fancybox.jquery.plugin.js
        position: bottom

global_settings:
  hooks:
    modules_to_hook:
      displayHome:
        - ps_imageslider
        - ps_featuredproducts
        - ps_banner
        - ps_customtext
    custom_hooks:
      - name: displayProductCoverPlacement
        title: Product Cover Additionall Placement Element
        description: Add custom element on cover
      - name: displayProductThumbEndCustom
        title: Product Custom Thubnail on End
        description: Add custom image on end
      - name: displayCatalogBottom
        title: Catalog Bottom List
        description: Catalog after list hook display
      - name: displayInformationTop
        title: Catalog Product Top Information
        description: Catalog Product Top Information display hook
      - name: displayCatalogListProduct
        title: Category Product List
        description: Category Product List display hook
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#   js:
#     all:
#       - id: core.js
#         path: assets/js/core.js


  image_types:
    cart_default:
      width: 125
      height: 125
      scope: [products]
    small_default:
      width: 98
      height: 98
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 452
      height: 452
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 250
      height: 250
      scope: [products]
    large_default:
      width: 800
      height: 800
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 141
      height: 180
      scope: [products, categories]
    category_default_x2:
      width: 141
      height: 180
      scope: [products, categories]
    product_thumbnail: 
      width: 250
      height: 250
      scope: [products]
    stores_default:
      width: 170
      height: 115
      scope: [stores]