name: feeby
display_name: Feeby template
version: 1.0.0
parent: at_movic
assets:
  use_parent_assets: false
#  css:
#    all:
#      - id: custom-lib-style
#        path: assets/css/custom-lib.css
#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#   js:
#     all:
#       - id: core.js
#         path: assets/js/core.js