name: feeby
display_name: Feeby template
version: 1.0.0
parent: at_movic

assets:
  use_parent_assets: false

global_settings:
  configuration:
    PS_IMAGE_QUALITY: png
  modules:
   to_disable:
     - ps_contactinfo
     - ps_mainmenu
     - ps_imageslider
     - ps_featuredproducts
     - ps_banner
     - ps_customtext
     - productcomments
     - ps_linklist
  hooks:
    modules_to_hook:
      displayFooterNoIndexCartCheckout:
        - ps_emailsubscription
      displayNav1:
        - appagebuilder
      displayNav2:
        - appagebuilder
      displayTop:
        - appagebuilder
      displayHome: 
        - leoblog
      displayFooterBefore:
        - appagebuilder
      displayFooter:
        - appagebuilder
      actionAdminBefore:
        - appagebuilder
        - leobootstrapmenu
        - leoslideshow
        - leoblog
        - leofeature
        - blockgrouptop
        - leoquicklogin
        - leoproductsearch
        - leoextratab
  image_types:
    cart_default:
      width: 125
      height: 157
      scope: [products]
    small_default:
      width: 98
      height: 123
      scope: [products, categories, manufacturers, suppliers]
    medium_default:
      width: 378
      height: 472
      scope: [products, manufacturers, suppliers]
    home_default:
      width: 378
      height: 472
      scope: [products]
    large_default:
      width: 800
      height: 1000
      scope: [products, manufacturers, suppliers]
    category_default:
      width: 360
      height: 360
      scope: [categories]
    stores_default:
      width: 170
      height: 115
      scope: [stores]
    manu_default:
      width: 98
      height: 98
      scope: [manufacturers]
