name: feeby
display_name: Feeby template
version: 1.0.0
parent: at_movic
assets:
  use_parent_assets: false
  css:
    all:
      - id: main-style
        path: assets/css/styles.min.css
      - id: menu-style
        path: assets/css/menu.css
      - id: swiper-style
        path: assets/css/swiper.css
  js:
    order:
     - id: jquery-plugin-mask-js
       path: assets/js/jquery.mask.min.js
    product:
     - id: adding-to-cart-anim-js
       path: assets/js/adding-to-cart-anim.js
    all:
     - id: swiper-js
       path: assets/js/swiper.js
     - id: loader-js
       path: assets/js/loader.js
    product:
     - id: adding-to-cart-anim-js
       path: assets/js/adding-to-cart-anim.js
     - id: product-configure-js
       path: assets/js/product-configure.js
    all:
     - id: swiper-js
       path: assets/js/swiper.js
     - id: loader-js
       path: assets/js/loader.js

global_settings:
  hooks:
    custom_hooks:
      - name: displayProductCoverPlacement
        title: Product Cover Additionall Placement Element
        description: Add custom element on cover
      - name: displayProductThumbEndCustom
        title: Product Custom Thubnail on End
        description: Add custom image on end
      - name: displayCatalogBottom
        title: Catalog Bottom List
        description: Catalog after list hook display
      - name: displayInformationTop
        title: Catalog Product Top Information
        description: Catalog Product Top Information display hook
      - name: displayCatalogListProduct
        title: Category Product List
        description: Category Product List display hook
        

#    product:
#      - id: product-style
#        path: assets/css/product.css
#        media: all
#        priority: 200
#   js:
#     all:
#       - id: core.js
#         path: assets/js/core.js
