name: feeby
display_name: Feeby template
version: 1.0.0
parent: at_movic
assets:
  use_parent_assets: false
  css:
    all:
      - id: main-style
        path: assets/css/styles.min.css
      - id: menu-style
        path: assets/css/menu.css
      - id: swiper-styles
        path: assets/css/swiper.css
  js:
    all:
     - id: swiper-js
       path: assets/js/swiper.js

global_settings:
  hooks:
    custom_hooks:
      - name: displayProductThumbStartCustom
        title: Product Custom Thubnail on Start
        description: Add custom image on start
      - name: displayProductThumbEndCustom
        title: Product Custom Thubnail on End
        description: Add custom image on end
