name: Deploy on test

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-18.04
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        with:
          fetch-depth: 2
      
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
          
      - uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install dependency in theme
        run: npm install && npm run deploy

      - name: Remove node
        run: sudo rm -rf node_modules | ls -la

      - name: Deploy to Server
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -azr --delete --exclude={"/node_modules","/cache",".*"} --dry-run --stats --progress -vv
          remote_path: ${{ secrets.TARGET }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_port: ${{ secrets.REMOTE_PORT }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: './'
          # remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}
# TODO: Implement SSH for speed of deployment
#      - name: Deploy to Server
#        uses: easingthemes/ssh-deploy@v2.1.5
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          ARGS: "-rlgoDzvc --delete"
#          SOURCE: ${{ secrets.SOURCE }}
#          TARGET: ${{ secrets.TARGET }}
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}
#          EXCLUDE: "/dist/, /node_modules/, /cache/, /.git/, /.github/"

      # - name: Deploy to Server SFTP
      #   uses: wlixcc/SFTP-Deploy-Action@v1.0
      #   with:
      #     username: ${{ secrets.REMOTE_USER }}
      #     server: ${{ secrets.REMOTE_HOST }}
      #     port: ${{ secrets.REMOTE_PORT }}
      #     ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
      #     local_path: './*'
      #     remote_path: ${{ secrets.TARGET }}
      #     args: '-o ConnectTimeout=5'